language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker

before_install:
  - docker build -t reem-test -f Dockerfile.dev .

script:
  - docker run reem-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test-ci-cd"
  env: "Testcicd-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-283708364124"
  bucket_path: "test-ci-cd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
